#!/usr/bin/env ruby

require_relative './Workload/OptionParser.rb'
require_relative './Workload/Manager.rb'

class Main
  def initialize
    option_parser = OptionParser::OptionParser.new(ARGV)
    manager = Manager::Manager.new
    main(option_parser, manager)
  end

  def main(option_parser, manager)
    case option_parser.opts[:command]
    when :init
      manager.init(option_parser.opts[:file])
    when :build
      manager.build(option_parser.opts[:build])
    when :set
      manager.set(option_parser.opts[:set])
    when :var_list
      manager.var_list()
    when :repo_list
      manager.repo_list()
    when :status
      manager.status(option_parser.opts[:status])
    when :log 
      manager.log(option_parser.opts[:log])
    when :help
      manager.help()
    when :publish
      manager.publish()
    when :clone
      manager.clone()
    else 
      puts "ERROR: Invalid Operation"
    end
  end
end

Main.new
