#!/home/luiss/.rvm/wrappers/ruby-2.7.2@project/ruby
require_relative './lib/option_parser.rb'
require_relative './lib/manager.rb'

class Main
  def initialize
    option_parser = OptionParser::OptionParser.new(ARGV)
    manager = Manager::Manager.new
    main(option_parser, manager)
  end

  def main(option_parser, manager)
    case option_parser.opts[:command]
    when :init
      manager.init(option_parser.opts[:file])
    when :build
      manager.build(option_parser.opts[:build])
    when :set
      manager.set(option_parser.opts[:set])
    when :var_list
      manager.var_list()
    when :repo_list
      manager.repo_list()
    when :status
      manager.status()
    when :log 
      manager.log(option_parser.opts[:log])
    when :help
      manager.help()
    when :publish
      manager.publish()
    when :clone
      manager.clone(option_parser.opts[:clone])
    when :git
      manager.internal_git(option_parser.opts[:git])
    else 
      puts "ERROR: Invalid Operation"
    end
  end
end

Main.new
