#!/usr/bin/env ruby
require_relative './lib/option_parser.rb'
require_relative './lib/manager.rb'
require_relative './lib/helpers.rb'
require_relative './lib/webserver.rb'
class Main
  def initialize
    args = ARGV.clone
    Signal.trap("SIGPIPE") do
      Helper.lock_mg(:UNLOCK, args)
      exit
    end
    Helper.check_environment(args)
    Helper.lock_mg(:LOCK, args)

    begin
      opt = OptionParser::OptionParser.new
      option_parser_default_initializer(opt)
      option_parser_conditions_initializer(opt)
      Helper.lock_mg(:UNLOCK, args)
    rescue SignalException
      Helper.lock_mg(:UNLOCK, args)
    rescue Exception => e
      puts e
      Helper.lock_mg(:UNLOCK, args)
    rescue Interrupt
      Helper.lock_mg(:UNLOCK, args)
    rescue EPIPE
      Helper.lock_mg(:UNLOCK, args)
    end
  end

  def option_parser_conditions_initializer(opt)

    opt.condition("sources get ${name}")                    { |opts| Source.get_sources(opts[:name]) }
    opt.condition("sources delete <name>")                  { |opts| Source.delete_sources(opts[:name]) }
    opt.condition("sources list")                           { |opts| Source.list_sources() }
    opt.condition("sources show")                           { |opts| Source.show_sources() }
    opt.condition("sources pull {name}")                    { |opts| Source.pull_sources(opts[:name]) }
    opt.condition("sources <name> git <gitcommand>")        { |opts| Source.git_sources(opts[:name], opts[:gitcommand]) }

    opt.condition("saveconfig <pathtosave>")                { |opts| Config.save_config(opts[:pathtosave]) }
    opt.condition("clone <gitrepo> <dir>")                        { |opts| GitManager.get_clone_framework(opts[:gitrepo], opts[:dir]) }

    opt.condition("init <folderpath>")                      { |opts| Config.init_bsf(opts[:folderpath]) }

    opt.condition("vars")                                   { |opts| VarManager.instance.var_list() }
    opt.condition("tasks")                                  { |opts| puts Manager.instance.tasks_list() }
    opt.condition("set <var>=<value>")                      { |opts| VarManager.instance.set(opts[:var], opts[:value]); VarManager.instance.save }

    opt.condition("execute {-y} ${task}")                   { |opts| Manager.instance.build(opts[:task], opts[:y]) }

    opt.condition("publish")                                { |opts| Manager.instance.publish() }
    opt.condition("diff <hash1> {hash2}")                   { |opts| puts Manager.instance.diff(opts[:hash1], opts[:hash2]) }
    opt.condition("git $<gitcommand>")                      { |opts| GitManager.internal_git(opts[:gitcommand]) }

#    opt.condition("search $<var>=<value>")                  { |opts| GitManager.search_log(opts[:hash]) }
    opt.condition("search $<search>")                  	    { |opts| puts GitManager.search_log(opts[:search]) }

#    opt.condition("compare {-o} <task> <hash1> {hash2}")    { |opts| puts Manager.instance.compare(opts[:hash1], opts[:hash2], opts[:o], opts[:task])  }
    opt.condition("compare all $<args>")    		            { |opts| puts Manager.instance.compare_agregator(opts[:args]) }
    opt.condition("compare <task> $<args>")    		          { |opts| puts Manager.instance.compare(opts[:task], opts[:args]) }
 #   opt.condition("compare $<args>")    		    { |opts| puts Manager.instance.compare(opts[:args]) }


 #   opt.condition("compare all {-o} <hash1> {hash2}")       { |opts| puts Manager.instance.compare(opts[:hash1], opts[:hash2], opts[:o])  }

    opt.condition("server ${options}")                      { |opts| WebServer.execute(opts[:options]) }

    opt.condition("log {-f} <task> {hash}")                 { |opts| puts Manager.instance.log(opts[:task], opts[:hash], opts[:f]) }
    opt.condition("status {hash} ")                         { |opts| puts Manager.instance.status(opts[:hash]) }

    opt.condition("clean {-y} ${task}")                     { |opts| Manager.instance.clean(opts[:task], opts[:y]) }
    opt.condition("ls <task> {commit_id}")                  { |opts| puts Manager.instance.ls(opts[:task], opts[:commit_id]) }

    opt.condition("cat <task> <file> {commit_id}")          { |opts| puts Manager.instance.cat(opts[:task], opts[:commit_id], opts[:file]) }

    opt.parse(ARGV)
  end


  def option_parser_default_initializer(opt)

    opt.default do
      puts <<-EOF
usage: bsf <command>

These are the BSF commands used in various situations:

Start a working Environment
    init <folderpath>                  Create a new Framework Environment
    clone <gitrepo> <dir>              Clone an existing Framework Environment to a directory

Work with task/s
    execute ${task}                    Execute the task's execution instruction
    log {-t} <task>                    Print or follow the task's log
    status                             Lists the status of all tasks
    tasks                              Lists all the tasks and its description

Work with Input Variables
    set <var>=<value>                  Defines the value to the input variable
    vars                               Lists all the Input Variables and its value

Work with lists
    tasks                              Lists all the tasks and its description
    vars                               Lists all Input Variables

Work with the Git Repositories
    sources get ${name}                Clone a new Source to the framework environment
    sources delete <name>              Delete a Source from the framework environment
    sources list                       List all the Sources in the config file
    sources show                       Show all cloned the Sources in the framework environment

Work with Git
    git $<gitcommand>                  Execute internal git commands
    publish                            Adds and commits with a specific commit message to local git repository
    search $<var>=<value>              Searchs on git log's commit message

Work with comparation
    compare <task> <hash1> {hash2}     Compares test from hash1 to hash2 (Or LOCAL if hash2 not given)

Extra commands
    saveconfig <pathtosave>            Saves internal config with dependencies to pathtosave
    clean {-y} ${task}                 Cleans workspace folder, logs and resets status



	{} Optional Argument		<> Mandatory Argument		$ Capable of multiple Arguments

EOF
    end
  end


end

Main.new
